version: 2.1

executors:
  default:
    working_directory: ~/eslint-plugin-editorconfig
    docker:
      - image: phanect/ci-javascript

commands:
  init:
    steps:
      - run:
          name: System Update
          command: |
            sudo apt-get update -qq
            DEBIAN_FRONTEND=noninteractive sudo apt-get dist-upgrade --yes
            sudo npm install --global npm
      - checkout
      - run: yarn install

jobs:
  build:
    executor:
      name: default
    steps:
      - init
      - run: npm test
      - run: npx eslint .

  release:
    executor:
      name: default
    steps:
      - init
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > "$HOME/.npmrc"
          npm publish . --access public

workflows:
  version: 2.1
  build-n-release:
    jobs:
      - build:
          filters: # Run when any branches & tags pushed
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /^v.*/
            # By default, release runs on push to any branches.
            # To avoid running release, it is required to ignore all branches here.
            branches:
              ignore: /.*/
          requires:
            - build
